DECLARE 
v_col_type NUMBER;

BEGIN
SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_complain';--查出投诉管理的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '投诉管理' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_serve';--查出服务工单的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '服务工单' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_canvass_tel';--查出客户招揽的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '客户招揽' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_sale_opportunity';--查出销售机会的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '销售机会' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_potential';--查出潜客开发的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '潜客开发' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_questionnaire_myTask';--查出问卷调查的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '问卷调查' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_insure_orders';--查出保险订单的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '保险订单' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_canvass';--查出保险招揽的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '保险招揽' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_order';--查出电话下单的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '电话下单' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_maintain';--查出维修工单的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '维修工单' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_callback';--查出回访管理的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '回访管理' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

SELECT FI.FUNC_ID into v_col_type FROM FUNCTION_INFO FI WHERE FI.FUNC_FLAG='cube_questionnaire_history';--查出调查历史的模块ID
UPDATE BUSINESS_CLASS BC 
SET BC.APP_MODULE_ID = v_col_type 
WHERE BC.NODE_NAME = '调查历史' AND BC.BUSINESS_TYPEID = 6;--修改APP_MODULE_ID
COMMIT;

END;